### ISSUE TITLE
Integrate with Travis

### ISSUE THREAD

**Issue by gdalmau** [gdalmau/url_shortener#1]
Integrate with [Travis-CI](https://travis-ci.org/) to run the tests

**Comment by sowmiyamuthuraman** [comment]
I would like to work on this?

**Comment by gdalmau** [comment]
@sowmiyamuthuraman Sure 😄 

Feel free to PR the project adding the `.travis.yml` to run the tests as explained in [README](https://github.com/gdalmau/url_shortener/blob/master/README.md#running-tests) in python 3.6 and 3.7.
